server:
  port: 10000


name:
  service:
    url: http://localhost:10000


custom:
  datasource:
    url: jdbc:mysql://localhost:3306/simple?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234